version: 0.2
phases:
  install:
    runtime-versions:
      php: 8.2
  pre_build:
    commands:
      # Install Composer
      - sudo apt update -y 
      - curl -sS https://getcomposer.org/installer | php
      - mv composer.phar /usr/local/bin/composer
      - chmod +x /usr/local/bin/composer 
      - sudo apt install apache2 -y 
  build:
    commands:
      # Navigate to your PHP project directory
      - cd /var/www/html      # Install project dependencies using Composer
      - composer install
artifacts:
  files:
    - '**/*'
  base-directory: /var/www/html
